# fly.toml app configuration file generated for comptable-clicker on 2025-04-22T20:25:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comptable-clicker'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8081'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
